1.Create a 3x3x3 array with random values

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.76233516 0.45009662 0.59465952]
  [0.20183124 0.03547147 0.39590956]
  [0.6472468  0.25318953 0.02740763]]

 [[0.76475684 0.95992149 0.12041864]
  [0.10298395 0.53009433 0.24853788]
  [0.91558177 0.72225902 0.72853812]]

 [[0.30943627 0.42360938 0.54904003]
  [0.65474291 0.34552457 0.16557157]
  [0.66022089 0.63928638 0.64392417]]]


2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


4.  Normalize a 5x5 random matrix

In [7]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.92985269 0.16176977 0.17259714 0.155345   0.20984459]
 [0.         0.48999218 0.95606219 0.10477342 0.20016657]
 [0.72772217 0.54476332 0.57892501 0.05859435 0.61640194]
 [0.28678573 0.67551206 1.         0.67366078 0.64938746]
 [0.60399066 0.56099483 0.19933087 0.83650385 0.2759367 ]]


5. How to find common values between two arrays?¶

In [8]:

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


6.How to get the dates of yesterday, today and tomorrow?

In [9]:

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


7. Consider two random array A and B, check if they are equal

In [10]:
an_array = np.array([[1,2],[3,4]])
another_array = np.array([[1,2],[3,4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

True


8.Create random vector of size 10 and replace the maximum value by 0

In [12]:

x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.84369565 0.47045451 0.4705265  0.77543176 0.84987678 0.31874007
 0.96985061 0.11524858 0.43422452 0.58502074 0.74821348 0.35556243
 0.26894615 0.63457058 0.05367044]
Maximum value replaced by 0:
[0.84369565 0.47045451 0.4705265  0.77543176 0.84987678 0.31874007
 0.         0.11524858 0.43422452 0.58502074 0.74821348 0.35556243
 0.26894615 0.63457058 0.05367044]


9. How to print all the values of an array?

In [13]:
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

10.Subtract the mean of each row of a matrix

In [14]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.17163595 0.94466512 0.72665562 0.87017626 0.70780681 0.32692187
  0.92407402 0.7556365  0.69913782 0.74227253]
 [0.95160593 0.98011809 0.19968013 0.16529072 0.20289183 0.48408961
  0.22029301 0.27369874 0.65989893 0.38225168]
 [0.68732389 0.58795383 0.79830868 0.2487695  0.05438083 0.88299366
  0.53485597 0.92034993 0.88331193 0.60558318]
 [0.9771741  0.44586296 0.96620225 0.71846884 0.94013108 0.65532214
  0.29023473 0.09420942 0.68980189 0.20691913]
 [0.89924851 0.61632367 0.89132567 0.41665129 0.28045984 0.57428668
  0.15226802 0.50392133 0.48789248 0.7945955 ]]

Subtract the mean of each row of the said matrix:

[[-0.5152623   0.25776687  0.03975737  0.18327801  0.02090856 -0.35997638
   0.23717577  0.06873825  0.01223957  0.05537428]
 [ 0.49962406  0.52813622 -0.25230174 -0.28669114 -0.24909004  0.03210774
  -0.23168886 -0.17828313  0.20791707 -0.06973018]
 [ 0.06694075 -0.03242931  0.17792554 -0.37161364 -0.56600231  0.26261052
  -0.08552717  0.29996679  0.2

13.How to find the most frequent value in an array?

In [15]:

x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[1 7 0 8 0 4 8 6 3 5 0 1 7 6 3 9 2 5 2 4 9 7 3 9 3 6 1 7 7 9 0 7 4 0 0 8 4
 8 0 4]
Most frequent value in the above array:
0


14.How to get the n largest values of an array

In [17]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


15.How to create a record array from a regular array?

In [19]:

a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
